// 「立ち上げチェック報告書」スプレッドシートから生成した初期データ
window.RAKU_SEED = {
  templates: [
    { id: "toriyaro", name: "鶏ヤロー（直営）", tasks: [
      {"t":"保健所","who":"近藤"},
      {"t":"消防署","who":"近藤"},
      {"t":"監視カメラ","who":"近藤"},
      {"t":"バイト募集15","who":"店舗 / サポート"},
      {"t":"リゾートバイト","who":"店舗 / サポート"},
      {"t":"ハローワーク求人","who":"店舗 / サポート"},
      {"t":"新規店選挙","who":"店舗 / サポート"},
      {"t":"業者一覧シート記入(時間、管理会社、鍵番号)","who":"店舗 / サポート"},
      {"t":"グーグルマイビジネス","who":"店舗 / サポート"},
      {"t":"オープン日","who":"店舗 / サポート"},
      {"t":"テナント保険加入","who":"店舗 / サポート"},
      {"t":"各店舗のフリーWi-Fi","who":"店舗 / サポート"},
      {"t":"ホットペッパー","who":"店舗 / サポート"},
      {"t":"オープン集客インフルエンサー / 30万分馬淵先生","who":"立ち上げ / 部隊"},
      {"t":"看板発注","who":"店舗 / サポート"},
      {"t":"店内暖色電球、提灯","who":"店舗 / サポート"},
      {"t":"看板","who":"店舗 / サポート"},
      {"t":"アンディ確認","who":"店舗 / サポート"},
      {"t":"ファサード電球暖色","who":"店舗 / サポート"},
      {"t":"Google口コミQR POP","who":"店舗 / サポート"},
      {"t":"廃油業者","who":"立ち上げ / 部隊","h":0.5},
      {"t":"おしぼり業者","who":"立ち上げ / 部隊","h":0.5},
      {"t":"ネクストワン","who":"立ち上げ / 部隊","h":0.1},
      {"t":"らくしふ","who":"立ち上げ / 部隊","h":0.1},
      {"t":"ぴかいちナビ","who":"立ち上げ / 部隊","h":0.1},
      {"t":"チビック登録","who":"立ち上げ / 部隊","h":0.1},
      {"t":"コネット","who":"立ち上げ / 部隊","h":0.1},
      {"t":"ゴミ業者","who":"立ち上げ / 部隊","h":0.5},
      {"t":"粗大ごみゴミ回収手配","who":"立ち上げ / 部隊","h":0.5},
      {"t":"乾物","who":"立ち上げ / 部隊","h":1.0},
      {"t":"八百屋","who":"立ち上げ / 部隊","h":1.0},
      {"t":"肉屋","who":"立ち上げ / 部隊","h":1.0},
      {"t":"オリジナルTシャツ","who":"立ち上げ / 部隊","h":0.1},
      {"t":"洗剤手配、、マット","who":"立ち上げ / 部隊","h":0.2},
      {"t":"皿発注","who":"立ち上げ / 部隊","h":5.0},
      {"t":"買い物リスト手配(豊栄)","who":"立ち上げ / 部隊","h":3.0},
      {"t":"えびせんボックス","who":"立ち上げ / 部隊","h":0.2},
      {"t":"テキーラベル発注、POP","who":"立ち上げ / 部隊","h":0.5},
      {"t":"コーラサーバー","who":"立ち上げ / 部隊","h":1.0},
      {"t":"ビールサーバー","who":"立ち上げ / 部隊","h":1.0},
      {"t":"フライヤーデバイス","who":"立ち上げ / 部隊","h":0.1},
      {"t":"看板つけっぱなし確認","who":"立ち上げ / 部隊","h":1.0},
      {"t":"図面共有","who":"立ち上げ / 部隊","h":2.0},
      {"t":"工事依頼申請","who":"店舗 / サポート"},
      {"t":"ガス工事","who":"近藤"},
      {"t":"キッチン設備購入","who":"近藤"},
      {"t":"厨房機器設置","who":"近藤"},
      {"t":"電気、ガス、水道","who":"近藤"},
      {"t":"エアータオル","who":"近藤"},
      {"t":"フライヤーひっかけるやつ","who":"近藤"},
      {"t":"業務用電子レンジ","who":"近藤"},
      {"t":"看板同期確認","who":"店舗 / サポート"},
      {"t":"インターネット/電話","who":"立ち上げ / 部隊","h":1.0},
      {"t":"ハンディー、タブレットカバー、 / レジ","who":"立ち上げ / 部隊","h":1.0},
      {"t":"音楽の音量設定（ボリューム）","who":"立ち上げ / 部隊","h":1.0},
      {"t":"店内音楽（おとらく導入）","who":"立ち上げ / 部隊","h":1.0},
      {"t":"スピーカー、音楽（申請したか）","who":"立ち上げ / 部隊","h":1.0},
      {"t":"Uレジ設定、モバイル設定","who":"立ち上げ / 部隊","h":5.0},
      {"t":"USENナンバーズ gmail","who":"立ち上げ / 部隊","h":1.0},
      {"t":"レシピ表作成","who":"立ち上げ / 部隊","h":1.0},
      {"t":"黄色い札","who":"立ち上げ / 部隊","h":1.0},
      {"t":"スタッフ紹介（〇〇賞）POP","who":"立ち上げ / 部隊","h":0.5},
      {"t":"ＰＯＰ手配","who":"立ち上げ / 部隊","h":0.2},
      {"t":"従業員QR、弁護士POP","who":"立ち上げ / 部隊","h":0.1},
      {"t":"身だしなみPOP、流れねーPOP","who":"立ち上げ / 部隊","h":0.1},
      {"t":"テキーラジュレ、やすいうるさい","who":"立ち上げ / 部隊","h":0.1},
      {"t":"ジョッキ手配(ロゴ入りか確認)","who":"立ち上げ / 部隊","h":0.1},
      {"t":"メニューブック作成","who":"立ち上げ / 部隊","h":0.1},
      {"t":"店長名刺","who":"立ち上げ / 部隊","h":0.2},
      {"t":"営業時間案内POP","who":"立ち上げ / 部隊","h":0.1},
      {"t":"弁護士ＰＯＰ","who":"立ち上げ / 部隊","h":0.1},
      {"t":"モバイルQR、 Wi-FiのPOP","who":"立ち上げ / 部隊","h":0.5},
      {"t":"パソコン","who":"立ち上げ / 部隊","h":0.2},
      {"t":"年齢確認タブレット設定","who":"立ち上げ / 部隊","h":0.2},
      {"t":"レストランボード","who":"立ち上げ / 部隊","h":0.5},
      {"t":"パスワード関係まとめる","who":"立ち上げ / 部隊","h":0.2},
      {"t":"レジ金、通帳","who":"盛さん","h":0.2},
      {"t":"日報","who":"立ち上げ / 部隊","h":2.0},
      {"t":"google年確のPOPと店舗名","who":"立ち上げ / 部隊","h":0.25},
      {"t":"ドリンク配置","who":"立ち上げ / 部隊","h":2.0},
      {"t":"POPはり","who":"立ち上げ / 部隊","h":7.0},
      {"t":"トイレセット","who":"立ち上げ / 部隊","h":0.5},
      {"t":"テーブルセット","who":"立ち上げ / 部隊","h":1.0},
      {"t":"名札","who":"立ち上げ / 部隊","h":0.1},
      {"t":"オペレーション","who":"立ち上げ / 部隊","h":5.0},
      {"t":"バイト研修","who":"立ち上げ / 部隊","h":5.0},
      {"t":"釣銭金75000円","who":"立ち上げ / 部隊","h":1.0},
      {"t":"両替","who":"立ち上げ / 部隊","h":0.5},
      {"t":"営業許可証のコピー貼り付け、事務所郵送","who":"立ち上げ / 部隊","h":0.5},
      {"t":"マスターキー事務所送付","who":""},
      {"t":"看板オープン日貼り付け","who":""},
      {"t":"コンセント増設","who":""},
    ] },
    { id: "fc", name: "FC", tasks: [
      {"t":"業者一覧シート記入(時間、管理会社、鍵番号)","who":"鶏ヤロー"},
      {"t":"指定ビール会社","who":"鶏ヤロー"},
      {"t":"テナント保険加入確認","who":"鶏ヤロー"},
      {"t":"指定乾物","who":"鶏ヤロー"},
      {"t":"指定八百屋","who":"鶏ヤロー"},
      {"t":"指定肉屋","who":"鶏ヤロー"},
      {"t":"廃油業者","who":"鶏ヤロー"},
      {"t":"唐揚げ粉、かけ粉、スパイシー粉確認","who":"鶏ヤロー"},
      {"t":"コカ・コーラ","who":"鶏ヤロー"},
      {"t":"契約書確認","who":"鶏ヤロー"},
      {"t":"契約金確認","who":"鶏ヤロー"},
      {"t":"消防署","who":"FCオーナー様"},
      {"t":"監視カメラ","who":"FCオーナー様"},
      {"t":"バイト募集15","who":"FCオーナー様"},
      {"t":"リゾートバイト","who":"FCオーナー様"},
      {"t":"ハローワーク求人","who":"FCオーナー様"},
      {"t":"グーグルマイビジネス","who":"FCオーナー様"},
      {"t":"オープン日","who":"FCオーナー様"},
      {"t":"物件担当ご招待","who":"FCオーナー様"},
      {"t":"各店舗のフリーWi-Fi","who":"FCオーナー様"},
      {"t":"ホットペッパー","who":"FCオーナー様"},
      {"t":"プレオープン集客","who":"FCオーナー様"},
      {"t":"看板発注","who":"FCオーナー様"},
      {"t":"店内暖色電球、提灯","who":"FCオーナー様"},
      {"t":"看板","who":"FCオーナー様"},
      {"t":"看板発注","who":"FCオーナー様"},
      {"t":"ファサード電球暖色","who":"FCオーナー様"},
      {"t":"SNS販促","who":"FCオーナー様"},
      {"t":"日報","who":"FCオーナー様"},
      {"t":"google年確のPOPと店舗名","who":"FCオーナー様"},
      {"t":"レジ金、通帳","who":"FCオーナー様"},
      {"t":"チビック登録","who":"FCオーナー様"},
      {"t":"スピーカー、音楽","who":"FCオーナー様"},
      {"t":"営業時間案内POP","who":"FCオーナー様"},
      {"t":"ゴミ業者","who":"FCオーナー様"},
      {"t":"インターネット/レジ導入","who":"FCオーナー様"},
      {"t":"粗大ごみゴミ回収手配","who":"FCオーナー様"},
      {"t":"電気、ガス、水道","who":"FCオーナー様"},
      {"t":"深夜営業許可証(都心部のみ)","who":"FCオーナー様"},
      {"t":"年齢確認タブレット設定","who":"FCオーナー様"},
      {"t":"コーラサーバー設置日","who":"FCオーナー様"},
      {"t":"ビールサーバー設置日","who":"FCオーナー様"},
      {"t":"工事依頼申請","who":"FCオーナー様"},
      {"t":"営業許可証のコピー貼り付け、事務所郵送","who":"FCオーナー様"},
      {"t":"オペレーション","who":"FCオーナー様"},
      {"t":"バイト研修","who":"FCオーナー様"},
      {"t":"皿発注","who":"FCオーナー様"},
      {"t":"ハンディー、タブレットカバー","who":"FCオーナー様"},
      {"t":"ガス工事","who":"FCオーナー様"},
      {"t":"レシピ表作成","who":"FCオーナー様"},
      {"t":"黄色い札","who":"FCオーナー様"},
      {"t":"レストランボード","who":"FCオーナー様"},
      {"t":"パスワード関係まとめる","who":"FCオーナー様"},
      {"t":"スタッフ紹介（〇〇賞）POP","who":"FCオーナー様"},
      {"t":"ＰＯＰ手配","who":"FCオーナー様"},
      {"t":"ドリンク配置","who":"FCオーナー様"},
      {"t":"音楽の音量設定","who":"FCオーナー様"},
      {"t":"キッチン設備購入","who":"FCオーナー様"},
      {"t":"厨房機器設置","who":"FCオーナー様"},
      {"t":"POPはり","who":"FCオーナー様"},
      {"t":"パソコン","who":"FCオーナー様"},
      {"t":"オリジナルTシャツ","who":"FCオーナー様"},
      {"t":"えびせんボックス","who":"FCオーナー様"},
      {"t":"店内音楽","who":"FCオーナー様"},
      {"t":"トイレセット","who":"FCオーナー様"},
      {"t":"ぴかいちナビ","who":"FCオーナー様"},
      {"t":"フライヤーデバイス","who":"FCオーナー様"},
      {"t":"テキーラベル発注、POP","who":"FCオーナー様"},
      {"t":"テーブルセット","who":"FCオーナー様"},
      {"t":"名札","who":"FCオーナー様"},
      {"t":"買い物リスト手配(豊栄)","who":"FCオーナー様"},
      {"t":"メニューブック作成","who":"FCオーナー様"},
      {"t":"らくしふ","who":"FCオーナー様"},
      {"t":"ジョッキ手配(ロゴ入りか確認)","who":"FCオーナー様"},
      {"t":"おしぼり業者","who":"FCオーナー様"},
      {"t":"ネクストワン","who":"FCオーナー様"},
      {"t":"店長名刺","who":"FCオーナー様"},
      {"t":"Uレジ設定、QR印刷","who":"FCオーナー様"},
      {"t":"モバイルQR、 Wi-FiのPOP","who":"FCオーナー様"},
      {"t":"エアータオル","who":"FCオーナー様"},
      {"t":"フライヤーひっかけるやつ","who":"FCオーナー様"},
      {"t":"業務用電子レンジ","who":"FCオーナー様"},
    ] },
  ],
  docs: [
    "法人登記簿謄本",
    "法人定款移し",
    "お店のメニュー",
    "法人役員、店長、身分証のコピー（免許証など顔写真付き）",
    "法人役員、店長の住民票、本籍地あり、マイナンバーなし",
    "賃貸借契約書の原本",
    "建物所有者からの使用承諾証",
    "店舗の図面（営業許可申請時に提出したもの）",
    "営業許可証の写し",
    "ある場合は店舗の照明、音響の図面",
    "・その他必要情報",
    "店舗名、住所、電話番号",
    "会社名、住所、電話番号",
    "店舗管理者の氏名、生年月日、住所電話番号",
    "営業時間、店舗入り口に18歳未満立ち入り禁止の掲示",
  ],
  stores: [
    {"name":"柏","method":"要確認","eisei":"和田 成司","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"松戸","method":"要確認","eisei":"近藤 光善","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"錦糸町","method":"要確認","eisei":"脇 北斗","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"溝の口","method":"要確認","eisei":"石井 槙人","bouka":"","note":"ウイザー","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"秋葉原","method":"要確認","eisei":"楠見 光祐","bouka":"楠見 光祐","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":true},
    {"name":"町田","method":"要確認","eisei":"近藤 光善","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"渋谷道玄坂","method":"要確認","eisei":"","bouka":"近藤 光善","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":true,"smoke":false},
    {"name":"渋谷駅前","method":"電子","eisei":"中林 伸太郎","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":true,"smoke":false},
    {"name":"大宮","method":"要確認","eisei":"","bouka":"辻 勝平","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"草加","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"北千住","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"池袋","method":"要確認","eisei":"近藤 光善","bouka":"近藤 光善","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":true,"smoke":false},
    {"name":"志木","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":true,"smoke":false},
    {"name":"川崎","method":"要確認","eisei":"邨井 裕己","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":true,"lnPermit":false,"smoke":false},
    {"name":"千葉","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"南越谷","method":"要確認","eisei":"楠見 光祐","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"津田沼","method":"要確認","eisei":"楠見 光祐","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"歌舞伎町","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":true,"smoke":false},
    {"name":"新宿西口","method":"要確認","eisei":"","bouka":"近藤 光善","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"船橋","method":"電子","eisei":"楠見 光祐","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"高田馬場","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"立川","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"立川北口","method":"電子","eisei":"中川 哲","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"魚鶏柏","method":"電子","eisei":"邨井 裕己","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"東小金井","method":"電子","eisei":"楠見 光祐","bouka":"楠見光祐","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"カラオケ池袋","method":"電子","eisei":"早坂 隆典","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":true,"smoke":false},
    {"name":"名古屋","method":"要確認","eisei":"近藤 光善","bouka":"","note":"ウイザー","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"魚鶏御徒町","method":"電子","eisei":"邨井 裕己","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"福島栄町","method":"要確認","eisei":"","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"名古屋栄","method":"要確認","eisei":"三島 強","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"魚鶏栄","method":"電子","eisei":"関 大地","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"魚鶏金山","method":"電子","eisei":"野中 俊宏","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"魚鶏八戸","method":"電子","eisei":"秋元 伊佐夫","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"いわき","method":"電子","eisei":"鈴木 慎吾","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"難波","method":"電子","eisei":"渡部 龍介","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":true,"lnPermit":false,"smoke":true},
    {"name":"仙台","method":"電子","eisei":"野中 俊宏","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"宇都宮","method":"電子","eisei":"田畑 広展","bouka":"","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"土浦","method":"電子","eisei":"菅裕貴","bouka":"菅裕貴","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"盛岡","method":"電子","eisei":"小野寛","bouka":"小野寛","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"藤沢","method":"電子","eisei":"中林伸太郎","bouka":"中林伸太郎","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"新橋","method":"電子","eisei":"山口将史","bouka":"山口将史","note":"","credit":true,"qr":true,"pay":true,"lnApply":true,"lnPermit":false,"smoke":true},
    {"name":"京都三条","method":"電子","eisei":"船津健留","bouka":"船津健留","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"心斎橋","method":"電子","eisei":"菊江祐哉","bouka":"菊江祐哉","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"京都西院","method":"電子","eisei":"大黒健太","bouka":"大黒健太","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"茶屋町","method":"電子","eisei":"頼末星弥","bouka":"頼末星弥","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"カラオケ町田","method":"電子","eisei":"坪倉正明","bouka":"坪倉正明","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"三宮B1F","method":"電子","eisei":"辻 勝平","bouka":"辻 勝平","note":"","credit":true,"qr":true,"pay":true,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"姫路","method":"電子","eisei":"石山卓弥","bouka":"石山卓弥","note":"","credit":false,"qr":false,"pay":false,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"三宮２F","method":"電子","eisei":"有田琉央","bouka":"有田琉央","note":"","credit":false,"qr":false,"pay":false,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"道頓堀","method":"","eisei":"稲月龍司","bouka":"稲月龍司","note":"","credit":false,"qr":false,"pay":false,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"新宿西口","method":"","eisei":"","bouka":"","note":"","credit":false,"qr":false,"pay":false,"lnApply":false,"lnPermit":false,"smoke":false},
    {"name":"歌舞伎3号店","method":"","eisei":"小沼博義","bouka":"小沼博義","note":"","credit":false,"qr":false,"pay":false,"lnApply":false,"lnPermit":false,"smoke":false},
  ],
};
